### ISSUE TITLE
:memo: TODO: Add support on how to check Missing Direct Credit Entries

### ISSUE THREAD

**Issue by Rexpert** [Rexpert/TNG_Statement_in_CSV#16]
As a user, I might not know where to find the Missing Direct Credit Entries and do not know how to input those entries into this program. 

Expectation:
A readme section on how to find direct credit entries on the TNG eWallet App and how to treat them in the [`main.py`](https://github.com/Rexpert/TNG_Statement_in_CSV/blob/main/main.py)

**Comment by andytan0727** [comment]
@Rexpert when to start this!

**Comment by Rexpert** [comment]
@andytan0727 SOON. Please Stay Tuned.
