### ISSUE TITLE
Identify coordinates in PDF

### ISSUE THREAD

**Issue by junhong0618** [Rexpert/TNG_Statement_in_CSV#2]
Hi, Rexpert bro. I noted you have self-specified `tables_areas` and `columns` when using `camelot.read_pdf()`. May I check how do you determine those coordinates from the PDF?

**Comment by Rexpert** [comment]
Hi @junhong0618 , I check the coordinate by plotting the pdf out, you need to install matplotlib to visualize the page. 

Run this code to visualize any page in the pdf (for eg: page 44)
> **`test/camelot_plot.py`**
> ```python
> import matplotlib.pyplot as plt
> from matplotlib.ticker import MultipleLocator
> import camelot
> 
> table = camelot.read_pdf(r'.\data\tng_ewallet_transactions.pdf', pages='44', flavor='stream',
>                          split_text=True, strip_text='\n')
> 
> fig, ax = plt.subplots()
> pg = camelot.plot(table[0], kind='text')
> yaxis = plt.gca().yaxis
> yaxis.set_major_locator(MultipleLocator(10))
> xaxis = plt.gca().xaxis
> xaxis.set_major_locator(MultipleLocator(10))
> xaxis.set_tick_params(labelrotation=90)
> plt.grid(True)
> pg.show()
> ```

This will output a plot as below:
![image](https://github.com/Rexpert/TNG_Statement_in_CSV/assets/46991185/6ef85d22-89b5-45b2-a2aa-a64694de719c)

Note the right hand side of the toolbar (red box) is the current coordinate of the mouse cursor. 

From here, I got the coordinate of the `table-areas` and the `columns` separations, then I fine tune the coordinate manually.

For more explanation, please visit camelot-py documentation: [Visual Debug](https://camelot-py.readthedocs.io/en/master/user/advanced.html#visual-debugging)

**Comment by junhong0618** [comment]
@Rexpert thanks for your assistance and clear guideline. I will close this issue.
