### ISSUE TITLE
Unable to read a particular page of pdf

### ISSUE THREAD

**Issue by junhong0618** [Rexpert/TNG_Statement_in_CSV#3]
Hi @Rexpert, good day to you. I need your kind assistance again.

I encountered an `IndexError: list index out of range` when I included one particular page from the pdf in the `camelot.read_pdf` syntax. This particular page is the start of `GO+ TRANSACTION` (attached screenshot below). If I exclude this page, there wont be any errors. I think the issue is related to the column coordinate setting `columns=['80,140,230,294,460,660,720']`. When I remove column setting, I can read all pages of pdf without error. If I want to include column setting, I must exclude this particular page of pdf. 

Is it possible the Index Error is due to the title `GO+ TRANSACTION`? But why the title `TNG WALLET TRANSACTION` at the first page does not face this issue? 

![image](https://github.com/Rexpert/TNG_Statement_in_CSV/assets/151898599/2a1c7339-6d81-4fee-a275-27c35ee40fab)

**Comment by Rexpert** [comment]
Good morning @junhong0618 

Based on my experience with this `IndexError`, I think the `table_regions` / `table_areas` parameter may be the main cause, because camelot couldn't find the number or found multiple table in the range. I suggest you to try switching `table_regions` or `table_areas` in your code.

For development purpose, please let me know if the fix work... Thank you

**Comment by junhong0618** [comment]
Thanks for the prompt assistance. As an update, after I replaced `table_regions` with `table_areas` and remained the same coordinates, the error is resolved. May I know how should I differentiate these 2 usages?

I am still confused even after reading the info from below link.
[[camelot](https://camelot-py.readthedocs.io/en/master/user/advanced.html#specify-table-regions)](https://camelot-py.readthedocs.io/en/master/user/advanced.html#specify-table-regions)

**Comment by Rexpert** [comment]
According to my understanding, the difference is `table_areas` used to specify **exact** table coordinates, but if specify `table_regions` will make camelot search table on the given coordinates.

> Based on my experience with this IndexError, I think the table_regions / table_areas parameter may be the main cause,

By the way, I've made this udate on c9b21ac, you can sync my repo (make pull request in your forked repo) in the github web interface and then run this code to sync your local repo
```
> git pull
```

P/S: Please don't close this issue, I'll make the improvement on the code with next commit update.

**Comment by junhong0618** [comment]
Noted. I wont be closing this issue. 

From my understanding, pull request to be created when I propose the change to the code owner. Since you have updated on https://github.com/Rexpert/TNG_Statement_in_CSV/commit/c9b21ac486e656134d48beb578cc280b8e9c8807, should I still create any pull request? Apologies for this question as I am new to Github.

**Comment by Rexpert** [comment]
Yes, when you forked my repo, you create a clone repo to your github. What I mean pull request here is you proposing a change (syncing my repo) to your owned repo. 
> junhong/TNG:main <-- Rexpert/TNG:main

Below is the demostration:
![image](https://github.com/Rexpert/TNG_Statement_in_CSV/assets/46991185/8fa62a03-072c-4b1d-8717-66108b356e79)

However, for a quicker way, I just knew we can directly sync the repo with the sync button, sorry I'm also still learning this Github thing. 
![image](https://docs.github.com/assets/cb-75616/mw-1440/images/help/repository/sync-fork-dropdown.webp)
Source: [Syncing a fork branch from the web UI](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui)

I think both way works.
