### ISSUE TITLE
:memo: TODO: Add support to new TNG statement

### ISSUE THREAD

**Issue by Rexpert** [Rexpert/TNG_Statement_in_CSV#6]
As a developer, the new format of the TNG Statement is easier to record and has solved the bug of the old TNG Statement, i.e.: Reversing Entry and Missing Direct Credit entry. However, we're unable to cross-check with the wallet balance, since the statement does not have the balance column.

The new statement can be downloaded via [TNG ePortal](https://eportal.touchngo.com.my/login)

The example columns of the new TNG Statement:
![image](https://github.com/user-attachments/assets/bf90464f-e24d-41c3-bdbe-e41a68648c57)

Meanwhile, the old version of the TNG Statement that can be requested to download via the TNG eWallet App is straightforward, we expect more user to download their statement using this method, hence we shouldn't abandon the support for old TNG Statement

**Comment by andytand** [comment]
@Rexpert mana this new support !

**Comment by Rexpert** [comment]
![Aqua Scream](https://media1.tenor.com/m/aeZfKyIJMfoAAAAC/aqua-scream-funny-face.gif)
